name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # LTS version preferred

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # for commenting on pull requests
          action: "upload"
          app_location: "/"                 # location of your app source code
          output_location: "build"          # location of the built app (React default)
